import { Metadata } from "next";
import "../styles.css";

export const metadata: Metadata = {
    title: 'About page',
    description: 'Generated by create next app',
}

const AboutPage = () => {
    return (
        <div className="main">
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odit ad voluptatibus animi velit ex, tempore laboriosam? Molestiae, dolorem, praesentium eligendi pariatur veniam voluptate dolorum expedita numquam magni voluptatem at ducimus.
        </div>
    )
}

export default AboutPage
